apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vhdfcyyuo-go 
  janus-idp.io/tekton: vhdfcyyuo-go
  backstage.io/kubernetes-id: vhdfcyyuo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vhdfcyyuo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  